victoire_core:
    widgets:
        text:
            class: "Victoire\TextBundle\\Entity\\WidgetText"
            name: text

jms_translation:
    configs:
        victoire_text_bundle:
            dirs: ["@VictoireTextBundle"]
            output_dir: "@VictoireTextBundle/Resources/translations"
