victoire_core:
    widgets:
        text:
            class: "Victoire\Widget\TextBundle\\Entity\\WidgetText"
            name: text

jms_translation:
    configs:
        victoire_text_bundle:
            dirs: ["@VictoireWidgetTextBundle"]
            output_dir: "@VictoireWidgetTextBundle/Resources/translations"
