services:
    victoire_core.twig.widget_text_manager:
        class: Victoire\Widget\TextBundle\Widget\Manager\WidgetTextManager
        arguments: 
            - "@service_container"
            - "Text"

    widget_text_manager:
        alias: victoire_core.twig.widget_text_manager
        
    #alias to the entity
    victoire.widget.text:
        class: Victoire\Widget\TextBundle\Entity\WidgetText
    #alias to the form
    victoire.widget.form.text:
        class: Victoire\Widget\TextBundle\Form\WidgetTextType
        tags:
            - { name: form.type , alias: victoire_widget_form_text}
        